frspageid: 30333813 # DO NOT CHANGE THIS PAGEID unless the WP:FRS page is completely different ENWIKI 30333813
sentcountpageid: 63968536 # DO NOT CHANGE THIS PAGEID
gaguidelinesheaderpageid: 39007733 # DO NOT CHANGE THIS PAGEID unless the GA topics are now on a completely different page
apiendpoint: https://test.wikipedia.org/w/api.php
botusername: Yapperbot@Yapperbot