frspageid: # Page ID of the WP:FRS page
sentcountpageid: # Page ID of the page used to store the SentCount JSON
gaguidelinesheaderpageid: # Page ID of the page containing the GA guidelines header, that maps the topics to subtopics
editlimit: # A number representing the limit on the number of edits the bot can have.