frspageid: 110754 # DO NOT CHANGE THIS PAGEID unless the WP:FRS page is completely different
sentcountpageid: 110772 # DO NOT CHANGE THIS PAGEID
gaguidelinesheaderpageid: 110769 # DO NOT CHANGE THIS PAGEID unless the GA topics are now on a completely different page
apiendpoint: https://test.wikipedia.org/w/api.php
botusername: Yapperbot@Yapperbot